// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("API.Models.Chamado", b =>
                {
                    b.Property<string>("ChamadoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("ChamadoId");

                    b.ToTable("Chamados");

                    b.HasData(
                        new
                        {
                            ChamadoId = "f4a2b8d9-7c4e-4f8e-bdc9-9181e456ad0e",
                            CriadoEm = new DateTime(2025, 11, 24, 21, 4, 3, 488, DateTimeKind.Local).AddTicks(7643),
                            Descricao = "TESTE",
                            Status = "Aberto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
